### ISSUE TITLE
permission denied on CentOS - Podman emulator

### ISSUE THREAD

**Issue by Archer1411** [pg9182/northstar-dedicated#23]
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0...
Getting image source signatures
Copying blob a99c34865d99 skipped: already exists  
Copying blob 891382f67258 skipped: already exists  
Copying blob 617ce86479e7 skipped: already exists  
Copying blob 59bf1c3509f3 skipped: already exists  
Copying blob 1d676022bd00 skipped: already exists  
Copying blob aca1971a86b4 skipped: already exists  
Copying blob d8e612b3ace8 skipped: already exists  
Copying blob c49e47170caa skipped: already exists  
Copying config 760369964c done  
Writing manifest to image destination
Storing signatures
Northstar Dedicated Server - Docker (hostname: f7938bcd6dfe)

    https://northstar.tf
    https://northstar.tf/discord
    https://github.com/R2Northstar/Northstar
    https://github.com/pg9182/northstar-dedicated

Merging files...
Error: Failed to merge game files: merge titanfall: access "/mnt/titanfall/build.txt": stat /mnt/titanfall/build.txt: permission denied

**Comment by Archer1411** [comment]
CentOS 9 Stream

**Comment by pg9182** [comment]
Check your permissions on the mounted titanfall directory on the host.

**Comment by pg9182** [comment]
I am going to close this issue since there hasn't been a response. Feel free to re-open it if you are still having trouble.
