### ISSUE TITLE
Sever server lag introduced by patches in the last few days 

### ISSUE THREAD

**Issue by L1ghtman2k** [pg9182/northstar-dedicated#30]
One of the commits between: 9febe7ee772fd35b636421a421e9f506af83013b and 9fb610ea9a3ea94584525f3ec013c8c1b90b6a84 introduces severe server-side lag: https://streamable.com/8cl7x7

**Comment by L1ghtman2k** [comment]
reverting back to the image from 11 days ago (ghcr.io/pg9182/northstar-dedicated:1.20220502.git04c1bf6-tf2.0.11.0-ns1.7.0) fixed the issue

**Comment by L1ghtman2k** [comment]
closing for now, since i couldnt replicate on latest image

**Comment by pg9182** [comment]
Most likely fixed by 30b98634cd02aece8b490bea9606b2595d8de94f.
