### ISSUE TITLE
allow mounting for banlist.txt

### ISSUE THREAD

**Issue by pcbmaster** [pg9182/northstar-dedicated#34]
banlist is in the r2northstar folder, which is inaccessible from outside the docker container

**Comment by BulletMemes** [comment]
The banlist is located here `/usr/lib/northstar/R2Northstar/banlist.txt`.

**Comment by pcbmaster** [comment]
Oh nice, thanks.  Do you know the formatting of the banlist by chance?

**Comment by BulletMemes** [comment]
Here's the structure
![image](https://user-images.githubusercontent.com/22633480/169640631-eadd5602-d45b-462e-8fe7-4a15e261cf85.png)
