### ISSUE TITLE
Poor performance on multiple different machines since 1.9.4

### ISSUE THREAD

**Issue by pcbmaster** [pg9182/northstar-dedicated#42]
Not sure what's up, but I have had nothing but issues with stuttering and ping spikes since around 1.9.4.  Doesn't matter what arguments I give to Northstar, the server starts to chug around 6-7 connected players.  I have plenty of bandwidth, ram and CPU available.  Only thing of note is I am using `--network host` on the docker container.

**Comment by GeckoEidechse** [comment]
In order to debug this, could you maybe try running `v1.9.3` explicitly by using
`ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0-ns1.9.3 `
instead of
`ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0`
as your image? ^^

**Comment by pcbmaster** [comment]
Ran using 1.9.3, issue still persists.

**Comment by GeckoEidechse** [comment]
> Ran using 1.9.3, issue still persists.

Can you try the same with `v1.9.2` and if also broken lower the version until `v1.9.0` ^^

We need to figure out which version introduced the issue, to single out the cause for it.

**Comment by pcbmaster** [comment]
rolled all the way down to 1.9.0, incrementally.  No change to performance.

**Comment by GeckoEidechse** [comment]
Aight, that at least implies that the issue existed for a while. Given that I haven't really seen anyone else complain about it, it might specific to your setup. So anything you could share in terms of compose file or system specs would be appreciated <3

**Comment by pcbmaster** [comment]
Do not use `--network host`

**Comment by pg9182** [comment]
Huh? That should make it perform better if anything.
