### ISSUE TITLE
disable management features

### ISSUE THREAD

**Issue by sugoidogo** [pg9182/northstar-dedicated#8]
I need a docker container to provide only the runtime environment to run the NorthStar server. The only other container available doesn't work at all, so I need an option for this one (or alternate version) which only runs the server and does not attempt to manage the files or configuration, as I already have that set up outside the container and the options documented in the readme are insufficient.

**Comment by pg9182** [comment]
After discussing this on discord, I have decided to add an undocumented (and unsupported) option to use assembled game files from a mounted directory instead of the overlay and config logic.

**Comment by sugoidogo** [comment]
Another idea that occurred to me after our conversation was to add a mount point for config files ( specifically `ns_startup_args_dedi.txt` and `mods\Northstar.CustomServers\mod\cfg\autoexec_ns_server.cfg` since they contain all know vanilla config options that I'm aware of ) to allow all options on top of your container's features

**Comment by sugoidogo** [comment]
It also just now occurs to me, could I already include autoexec with your existing mods mount point? if so I guess the only real issue is the options used in `ns_startup_args_dedi.txt`.

**Comment by sugoidogo** [comment]
Testing my theory reveals that config path is specifically disallowed for overwriting. I would like to figure out a solution that allows NorthStar to be updated with the container if possible.

**Comment by pg9182** [comment]
@sugoidogo, if you have a prepared Northstar dir and you don't need Docker for anything, you can try my new [nswrap](https://github.com/pg9182/northstar-dedicated/blob/experimental-stuff/src/nswrap/nswrap.c) tool (compile it along with the gfsdk and d3d11 stubs, then create the wineprefix manually and launch it with nswrap).

**Comment by sugoidogo** [comment]
I don't know anything about C, do you have compiled binaries or build instructions?

**Comment by pg9182** [comment]
Which distro are you on?

**Comment by sugoidogo** [comment]
Proxmox. I'm most familiar with debian but I can spin up whatever distro is easiest.

**Comment by pg9182** [comment]
You can now do this with something like the following command: `docker run -v /path/to/northstar/installation:/northstar -e DISPLAY=xvfb -p 8081:8081/tcp -p 37015:37015/udp -it --entrypoint nswrap ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0-ns1.6.3 /northstar [args]`. You will need to ensure that the install directory is writable by UID 1000.

Note that you don't need to pin the container image to a specific northstar version, but I recommend doing so (to the corresponding version) just in case a future nswrap version breaks compatibility with your installation.
